version: "3"

services:

  php-fpm:
    container_name: moydom_phpfpm
    build:
      context: ./php-fpm
    volumes:
      - ./../../:/var/www/public/
    environment:
      XDEBUG_CONFIG: "remote_host=172.20.0.5 client_host=172.20.0.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"

  nginx:
    container_name: moydom_nginx
    build:
      context: ./nginx
    volumes:
      - ./../../:/var/www/public/
    ports:
      - 8080:80
    depends_on:
      - php-fpm
